version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:21.2.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - aws-cli/setup
      - run:
          name: Deploy to AWS S3
          command: | 
            aws s3 sync ./dist s3://$AWS_S3_BUCKET_NAME/ember-app --acl public-read --delete

workflows:
  build_and_deploy:
    jobs:
      - build-and-deploy
